# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d213dc59db895b7b58410a8c21a8f4b893b82ab2fa8f6e5ea3fe249425a7a7cab5e3a5d0571896bcc78c40b7d80d029239ae2b9e7cbfdb73cebe315293e5ab1b

test:
  secret_key_base: 3164e34fd40c4f8b690dc069b3461fe468be3267cf3d4d1c8bb7bad31700c34b15f5e2493bef16bc3d54742ee5fbd4c9b7bd0f77172c1ad612b56bb92c36b6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
